CREATE TABLE IF NOT EXISTS iam_departments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  department_code VARCHAR(64) NOT NULL UNIQUE,
  department_name VARCHAR(128) NOT NULL,
  parent_id BIGINT NULL,
  status ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE'
);
CREATE TABLE IF NOT EXISTS iam_positions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  position_code VARCHAR(64) NOT NULL UNIQUE,
  position_name VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS iam_users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  display_name VARCHAR(128) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  department_id BIGINT NULL,
  position_id BIGINT NULL,
  status ENUM('ACTIVE','LOCKED','DISABLED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS iam_roles (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  role_code VARCHAR(64) NOT NULL UNIQUE,
  role_name VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS iam_user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);
CREATE TABLE IF NOT EXISTS iam_role_permissions (
  role_id BIGINT NOT NULL,
  permission_code VARCHAR(128) NOT NULL,
  PRIMARY KEY (role_id, permission_code)
);
CREATE TABLE IF NOT EXISTS iam_audit_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  actor_user_id BIGINT NULL,
  action_code VARCHAR(128) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(128) NULL,
  detail_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
