CREATE TABLE IF NOT EXISTS knowledge_documents (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  document_type VARCHAR(64) NOT NULL DEFAULT 'business_definition',
  content LONGTEXT NOT NULL,
  status ENUM('TRAINING','TRAINED','FAILED') NOT NULL DEFAULT 'TRAINING',
  training_id VARCHAR(255) NULL,
  error_message VARCHAR(1000) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
